version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: mynginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
